const CITY_ALIASES=['مدينة السادات','السادات','سادات','sadat city','el sadat','el-sadat','alsadat'];
const DISTRICT_ALIASES={'المنطقة الأولى':['المنطقة الأولى','المنطقه الاولى','الأولى','الاولي','1st district'],'المنطقة الثانية':['المنطقة الثانية','المنطقه الثانيه','الثانية','الثانيه','2nd district'],'المنطقة الثالثة':['المنطقة الثالثة','المنطقه الثالثه','الثالثة','الثالثه','3rd district'],'المنطقة الرابعة':['المنطقة الرابعة','المنطقه الرابعه','الرابعة','الرابعه','4th district'],'المنطقة الخامسة':['المنطقة الخامسة','المنطقه الخامسه','الخامسة','الخامسه','5th district'],'المنطقة السادسة':['المنطقة السادسة','المنطقه السادسه','السادسة','السادسه','6th district'],'المنطقة السابعة':['المنطقة السابعة','المنطقه السابعه','السابعة','السابعه','7th district'],'المنطقة الثامنة':['المنطقة الثامنة','المنطقه الثامنه','الثامنة','الثامنه','8th district']};
function clean(v){return String(v??'').replace(/\s+/g,' ').trim()}
function normalizedText(v){return clean(v).toLowerCase().replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه')}
function normalizeDigits(v){return String(v??'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)))}
function firstMatch(t,p){for(const r of(Array.isArray(p)?p:[p])){const m=t.match(r);if(m)return m}return null}
function parseNumber(v){if(v==null)return null;const n=Number(normalizeDigits(v).replace(/[,،\s]/g,''));return Number.isFinite(n)?n:null}
function parseArea(text){const t=normalizeDigits(text);const m=firstMatch(t,[/(?:مساح(?:ة|ه)|مساحه)\s*(?:=|:|-)?\s*(\d+(?:\.\d+)?)\s*(?:م2|م²|متر(?:\s*مربع)?|sqm|m2)/i,/(\d+(?:\.\d+)?)\s*(?:م2|م²|متر(?:\s*مربع)?|sqm|m2)/i,/(?:مساح(?:ة|ه))\s*(\d+(?:\.\d+)?)\s*(?:متر|m)/i]);return m?parseNumber(m[1]):null}
function parseParcelNumber(text){const t=normalizeDigits(text);const m=firstMatch(t,[/(?:رقم\s*)?(?:القطعة|قطعه)\s*(?:رقم\s*)?(\d+)/i,/رقم\s*(\d+)\s*(?:مساحة|متر)/i]);return m?Number(m[1]):null}
function parseInstallmentsClear(text){return/(خالصة\s*الاقساط|خالصه\s*الاقساط|خلصت\s*الاقساط|مسدد(?:ة|ه)\s*الاقساط)/i.test(normalizedText(text))?true:null}
function parseBedrooms(text){const m=firstMatch(normalizeDigits(text),[/(\d+)\s*(?:غرف|غرفة|bedrooms?|beds?)/i,/(?:غرف|غرفة)\s*(?:عدد\s*)?(\d+)/i]);return m?Number(m[1]):null}
function parseBathrooms(text){const m=firstMatch(normalizeDigits(text),[/(\d+)\s*(?:حمام|حمامات|bathrooms?|baths?)/i,/(?:حمام|حمامات)\s*(?:عدد\s*)?(\d+)/i]);return m?Number(m[1]):null}
function parseFloor(text){const m=firstMatch(normalizeDigits(text),[/(?:الدور|طابق|floor)\s*([\wء-ي-]+)/i,/(?:floor\s*)(\d+)/i]);return m?clean(m[1]):null}
function parsePrice(text){const t=normalizeDigits(text);const m=firstMatch(t,[
  /(\d[\d,]*(?:\.\d+)?)\s*(مليار|billion)\s*([1-9]\d{0,2})\s*(?:جنيه|ج|egp|pounds?)?/i,
  /(\d[\d,]*(?:\.\d+)?)\s*(مليون|million)\s*([1-9]\d{0,2})\s*(?:جنيه|ج|egp|pounds?)?/i,
  /(\d[\d,]*(?:\.\d+)?)\s*(مليون|مليار|ألف|الف|million|billion|k)/i,
  /(?:للبيع|بيع|مطلوب|مطلوب\s*نهائي|نهائي|السعر|بسعر|price)\s*[:：-]?\s*(\d[\d,]*(?:\.\d+)?)/i,
  /(?:جنيه|ج|egp|pounds?)\s*(\d[\d,]*(?:\.\d+)?)/i
]);if(!m)return{price:null,currency:null};let amount=parseNumber(m[1]);if(amount==null)return{price:null,currency:null};const unit=normalizedText(m[2]||''),tail=m[3]?parseNumber(m[3]):null;if(unit==='مليون'||unit==='million')amount*=1_000_000;else if(unit==='مليار'||unit==='billion')amount*=1_000_000_000;else if(unit==='الف'||unit==='k')amount*=1_000;if(tail!=null&&(unit==='مليون'||unit==='million'))amount+=tail*1_000;if(tail!=null&&(unit==='مليار'||unit==='billion'))amount+=tail*1_000_000;return{price:amount,currency:'EGP'}}
function parseTransactionType(text){const n=normalizedText(text),sale=/(للبيع|بيع|مطلوب بيع|sale|for sale)/i.test(n),rent=/(للايجار|للتاجير|ايجار|تاجير|rent|for rent)/i.test(n);if(sale&&rent)return'both';if(sale)return'sale';if(rent)return'rent';return'unknown'}
function parsePropertyType(text){const n=normalizedText(text);if(/شقه|apartment|flat/i.test(n))return'apartment';if(/فيلا|villa/i.test(n))return'villa';if(/تاون هاوس|townhouse/i.test(n))return'townhouse';if(/توين هاوس|twin house/i.test(n))return'twin_house';if(/مكتب|اداري|office|administrative/i.test(n))return'office';if(/محل|shop|store|retail/i.test(n))return'shop';if(/ارض|أرض|land/i.test(n))return'land';if(/مخزن|warehouse|storage/i.test(n))return'warehouse';if(/عماره|عمارة|building/i.test(n))return'building';return'unknown'}
function parseFinishing(text){const n=normalizedText(text),v=[['super_lux',/سوبر لوكس|super\s*lux/i],['lux',/لوكس|lux/i],['good',/تشطيب جيد|جيد/i],['semi_finished',/نصف تشطيب|semi[- ]?finished/i],['unfinished',/على الطوب الاحمر|طوب احمر|unfinished/i],['fully_finished',/تشطيب كامل|fully finished/i]];return v.find(([,r])=>r.test(n))?.[0]??null}
function parseContact(text){const t=normalizeDigits(text),phone=t.match(/(?:\+?20\s?)?(?:01\d{9}|0?1\d{9}|1\d{9})/);if(!phone)return null;const digits=phone[0].replace(/\D/g,''),e164=digits.startsWith('20')?`+${digits}`:`+20${digits.replace(/^0/,'')}`;return{value:phone[0].trim(),normalized_value:e164}}
function parseDistrict(text){const n=normalizedText(text),numbered=n.match(/المنطقه\s*(\d{1,2})/i);if(numbered)return`المنطقة ${Number(numbered[1])}`;for(const[canonical,aliases]of Object.entries(DISTRICT_ALIASES))if(aliases.some(a=>n.includes(normalizedText(a))))return canonical;return null}
function parseCity(text){const n=normalizedText(text);return CITY_ALIASES.some(a=>n.includes(normalizedText(a)))?'مدينة السادات':null}
function inferTitle(p){const type=p.property_type==='unknown'?'عقار':p.property_type,action=p.transaction_type==='rent'?'للإيجار':p.transaction_type==='sale'?'للبيع':'عقاري';return`${type} ${action} — ${p.city||'غير محدد'}`}
function confidenceFor(p){const c=[Boolean(p.city),p.property_type!=='unknown',p.transaction_type!=='unknown',p.area_m2!=null,p.price!=null,p.bedrooms!=null,p.bathrooms!=null,Boolean(p.district),Boolean(p.parcel_number),Boolean(p.contacts?.length)];return Math.round(c.filter(Boolean).length/c.length*100)/100}
export function parseNaturalLanguageProperty(rawText){const raw=clean(rawText);if(!raw)throw new Error('raw_text_required');const price=parsePrice(raw),contact=parseContact(raw),parsed={property_type:parsePropertyType(raw),transaction_type:parseTransactionType(raw),status:'active',title:null,description:raw,city:parseCity(raw),district:parseDistrict(raw),neighborhood:null,address:null,latitude:null,longitude:null,area_m2:parseArea(raw),bedrooms:parseBedrooms(raw),bathrooms:parseBathrooms(raw),floor:parseFloor(raw),finishing:parseFinishing(raw),price:price.price,currency:price.currency||'EGP',features:{},confidence:0,contacts:contact?[contact]:[],parcel_number:parseParcelNumber(raw),installments_clear:parseInstallmentsClear(raw),unknown_fields:[]};if(parsed.parcel_number!=null)parsed.features.parcel_number=parsed.parcel_number;if(parsed.installments_clear!=null)parsed.features.installments_clear=parsed.installments_clear;parsed.title=inferTitle(parsed);parsed.confidence=confidenceFor(parsed);for(const[k,v]of Object.entries(parsed)){if(['title','description','currency','features','contacts','unknown_fields','confidence','status','parcel_number','installments_clear'].includes(k))continue;if(v==null||v==='unknown')parsed.unknown_fields.push(k)}return{parsed,validation:validatePropertyCandidate(parsed)}}
export function validatePropertyCandidate(c){const errors=[],warnings=[];if(!c.city)errors.push('city_required');if(c.city&&normalizedText(c.city)!==normalizedText('مدينة السادات'))errors.push('unsupported_city');if(c.price!=null&&c.price<=0)errors.push('price_invalid');if(c.area_m2!=null&&c.area_m2<=0)errors.push('area_invalid');if(c.parcel_number!=null&&c.parcel_number<=0)errors.push('parcel_number_invalid');if(c.bedrooms!=null&&c.bedrooms<0)errors.push('bedrooms_invalid');if(c.bathrooms!=null&&c.bathrooms<0)errors.push('bathrooms_invalid');if(!c.contacts?.length)warnings.push('no_contact_found');if(c.property_type==='unknown')warnings.push('property_type_unknown');if(c.transaction_type==='unknown')warnings.push('transaction_type_unknown');if(c.area_m2==null)warnings.push('area_missing');if(c.price==null)warnings.push('price_missing');if(c.parcel_number==null&&c.property_type==='land')warnings.push('parcel_number_missing');return{valid:errors.length===0,errors,warnings}}
export function buildIntakeEvent({channel='other',externalEventId=null,senderId=null,chatId=null,rawText}){const{parsed,validation}=parseNaturalLanguageProperty(rawText);return{channel,external_event_id:externalEventId,sender_id:senderId,chat_id:chatId,raw_text:clean(rawText),parsed_payload:{property:parsed,validation,parser:{name:'aqarat-deterministic-intake-v2',mode:'deterministic',created_at:new Date().toISOString()}}}}
export function propertyDedupKey(c){return[normalizedText(c.city||''),normalizedText(c.district||''),normalizedText(c.neighborhood||''),normalizedText(c.property_type||''),normalizedText(c.transaction_type||''),String(c.parcel_number??''),String(c.area_m2??''),String(c.price??''),String(c.bedrooms??''),String(c.bathrooms??'')].join('|')}
